[tool.poetry]
name = "airbnb-berlin-price-predic"
version = "0.1.0"
description = ""
authors = ["hajyhia <shehab.hajyhia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
